export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS'
export const GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST'
export const GET_BOOKS_FAILURE = 'GET_BOOKS_FAILURE'

export const PUT_BOOK_SUCCESS = 'PUT_BOOK_SUCCESS'
export const PUT_BOOK_REQUEST = 'PUT_BOOK_REQUEST'
export const PUT_BOOK_FAILURE = 'PUT_BOOK_FAILURE'

export const SEARCH_BOOK_SUCCESS = 'SEARCH_BOOK_SUCCESS'
export const SEARCH_BOOK_REQUEST = 'SEARCH_BOOK_REQUEST'
export const SEARCH_BOOK_FAILURE = 'SEARCH_BOOK_FAILURE'

export const CLEAR_SEARCH_BOOK = 'CLEAR_SEARCH_BOOK'